version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      # expose redis to machine for debugging
      - "6379:6379"

  observer:
    build:
      context: ../observer
      dockerfile: Dockerfile
    depends_on:
      - redis
    command: npm run start:dev
    volumes:
      - ../observer/app:/app
    environment:
      - NODE_ENV=development
      - REDIS_ENDPOINT=redis://redis:6379

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      - redis
    command: npm run start:dev
    ports:
      # expose api on port 4000
      - "4000:3000"
    volumes:
      - ../backed/app:/app
    environment:
      - PORT=3000
      - REDIS_ENDPOINT=redis://redis:6379

  frontend:
    depends_on:
      - backend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ../frontend/src:/app/src
      - ../frontend/public:/app/public
    command: npm start
    ports:
      # exposse ui on port 3000
      - "3000:3000"
    environment:
      NODE_ENV: development
      PROXY_URI: http://backend:3000
